name: Python Flake8 and pylint code quality check

on:
  workflow_call:
    inputs:
      black-version:
        required: false
        type: string
        default: '23.1.0'
      flake8-version:
        required: false
        type: string
        default: '3.8.4'
      pylint-version:
        required: false
        type: string
        default: '2.17.4'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install apt dependencies
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y -qq python3 python3-pip
    - name: Install pip dependencies
      run: |
        python -m pip install --upgrade pip
        pip3 install flake8==${{ inputs.flake8-version }}
        pip3 install pylint==${{ inputs.pylint-version }}
        pip3 install black==${{ inputs.black-version }}
        flake8 --version
        pylint --version
        black --version
    - name: Lint with Flake8
      run: |
        flake8 --config=.flake8 --count --statistics --show-source .
    - name: Lint with Pylint
      run: |
        pylint .
    - name: Lint with Pylint - More strict, allowed to fail
      run: |
        pylint --rc-file=.pylintrc_allowed_to_fail .
    - name: Check code style with Black
      run: |
        black --check --diff --line-length 79 .
